services:
  backend:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: gunicorn --bind 0.0.0.0:8010 app:app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3 